<a href="https://colab.research.google.com/github/CuteLoop/IntegrationWorkshop2024/blob/main/integration_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming Bootcamp: Day 1
## Basic Operations, Data Structures

Variables in Python are names that reference data stored in memory. They can hold different data types (like numbers, strings, or objects) and can be reassigned to new values at any time.
We assign data to a variable using the `=` sign.

In [ ]:
a = 1 # Integer -- notice how there are no decimals
b = 1.0 # Float -- this is CS speak for 'real number'. Integers will be stored as the float type if they include a decimal!
c = 1.0 + 0j # Complex number -- here `j` represents the complex part
d = '1' # String -- a sequence of characters meant to act like a word.
e = True # Bool -- short for Boolean, can be one of two values, True of False
f = [1,1] # List -- stores a sequence of data. The data could also be variables themselves.
g = (1,1) # Tuple -- also stores data, but has less structure than a list
h = range(1) # Range -- represents a sequence of numbers, typically used for iteration in loops.
i = {'one': 1} # # Dict -- stores data as key-value pairs, allowing for fast lookups by key.

How do these differ? They are all different data types. You can check the type of a variable by using `type(variable_name)`:

In [ ]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'range'>
<class 'dict'>


Each data type has a different set of operations, many of which use the same symbols. You need to know what type of data type you have in order to know what the operator will do. Most numeric types do exactly what you think they will!

In [ ]:
print(a+a)

2


In Python, you are sometimes allowed to perform operations between 2 different types of variables, this isn't the case in every language. It's important to know how it handles this. Play around with the cell below to see how different types get added together.

In [ ]:
a_plus_c = a+c
print(a_plus_c)
print(type(a_plus_c))
print(type(d + d))

(2+0j)
<class 'complex'>
<class 'str'>


Casting data types: it's possible to manually change the data type of a variable, an operation called "casting", but do so with caution. As is the case with all programming, order of operations is very important:

In [ ]:
# Converting a float to an integer
f = 5.7
int_f = int(f)  # Result is 5 (truncates the decimal part)
print("int_f:", int_f, type(int_f))

# Converting an integer to a string
num = 123
str_num = str(num)  # Result is '123'
print("str_num:", str_num, type(str_num))

# Converting a string to a float
str_float = "9.81"
float_value = float(str_float)  # Result is 9.81
print("float_value:", float_value, type(float_value))

# Casting a boolean to an integer
boolean_val = True
int_bool = int(boolean_val)  # Result is 1 (True converts to 1, False would convert to 0)
print("int_bool", int_bool, type(int_bool))

int_f: 5 <class 'int'>
str_num: 123 <class 'str'>
float_value: 9.81 <class 'float'>
int_bool 1 <class 'int'>
sol1 = 60
sol2 = 330
sol3 = 1815


In [ ]:
# Order of operations is important!
a = 5  # Integer
b = '3'  # String representing an integer

sol1 = (int(b) + int(b)) * (a + a)
sol2 = int(b + b) * (a + a)
sol3 = int(b + b) * int(str(a) + str(a))

print(f'sol1 = {sol1}')  # Sol1 performs integer addition and multiplication: (3 + 3) * (5 + 5) = 6 * 10 = 60
print(f'sol2 = {sol2}')  # Sol2 performs string concatenation first, then converts to int: int('33') * (5 + 5) = 33 * 10 = 330
print(f'sol3 = {sol3}')  # Sol3 performs string concatenation, converts back to int: int('33') * int('55') = 33 * 55 = 1815

sol1 = 60
sol2 = 330
sol3 = 1815


It's also possible to perform addition, subtraction, multiplication, exponentiation, and division between most numeric variable types.
Subtraction is performed with `-`, multiplication is performed with `*`, and exponentiation is performed with `**`:

In [ ]:
a = 5  # Integer
b = 2.0  # Float
c = 3 + 4j  # Complex number

# Addition
result_add = a + b  # 7.0 (integer + float)
print("Addition:", result_add)

# Subtraction
result_sub = b - a  # -3.0 (float - integer)
print("Subtraction:", result_sub)

# Multiplication
result_mul = a * c  # 15 + 20j (integer * complex)
print("Multiplication:", result_mul)

# Exponentiation
result_exp = a ** b  # 25.0 (integer ** float)
print("Exponentiation:", result_exp)

Addition: 7.0
Subtraction: -3.0
Multiplication: (15+20j)
Exponentiation: 25.0


There are three main operators used to perform division in Python:
the `/` operator will divide two numbers and return a floating point (real-valued) value, even if you are dividing two `int`s (this is different from many other programming languages, which will return an integer if two `int`s are divided):

In [ ]:
a = 10
b = 3

result1 = a / b  # Result is 3.3333333333333335 (float)
print(result1, type(result1))

c = 8
d = 4

result2 = c / d  # Result is 2.0 (float, even though both are ints)
print(result2, type(result2))

3.3333333333333335 <class 'float'>
2.0 <class 'float'>


The second operator is `//`, which returns the largest integer less than or equal to the quotient--in other words, it computes $\text{floor}\left(\frac{a}{b}\right)$. This operator will return an `int` value.

In [ ]:
a = 10
b = 3

result1 = a // b  # Result is 3 (int)
print(result1, type(result1))

c = 8
d = 3

result2 = c // d  # Result is 2 (int)
print(result2, type(result2))


3 <class 'int'>
2 <class 'int'>


The final way to divide numbers in Python is to use the modulus operator, `%`. This operator returns the integer remainder of the division of two numbers, i.e., it computes $a\mod b$:

In [ ]:
a = 10
b = 3

result1 = a % b  # Result is 1 (remainder of 10 divided by 3)
print(result1)

c = 8
d = 5

result2 = c % d  # Result is 3 (remainder of 8 divided by 5)
print(result2)

1
3


While you can perform mathematical operations on numeric data types, some other data types have special properties or operations that can be performed on them too. For example, the `str` (string) data type has many different useful features, such as concatenation, repetition, and various built-in methods for manipulation and formatting.

In [ ]:
# String concatenation
str1 = "Hello"
str2 = "World"
result = str1 + " " + str2  # Result is "Hello World"
print(result)

# String repetition
repeat_str = "Hi! "
result = repeat_str * 3  # Result is "Hi! Hi! Hi! "
print(result)

# Using a string method: converting to uppercase
original_str = "python is fun"
upper_str = original_str.upper()  # Result is "PYTHON IS FUN"
print(upper_str)

 # Indexing a string: selecting pieces of the string by their position
first_letter = original_str[0] # Result is 'p', the 1st letter in "python is fun". Notice the indices start at 0!
third_letter = original_str[2] # Result is 't', the 3rd letter in "python is fun".

first_word = original_str[0:6] # Result is 'python'. The syntax is string[start position : end position + 1]
print(third_letter)
print(first_letter)
print(first_word)

# Finding a substring
index = original_str.find("fun")  # Result is 10 (starting index of the substring "fun")
selected_fun = original_str[index:index+3] # "fun" is 3 letters long so we want to select 3 letters after the starting index
print(index)
print(selected_fun)

Hello World
Hi! Hi! Hi! 
PYTHON IS FUN
t
p
python
10
fun


# Basic Data Types and Operations Exercises

## Basic Exercises

1. Create two variables, one holding an integer and another holding a float. Perform addition, subtraction, multiplication, and division operations between them. Print the results and their types.

2. Given the string "Python", print its length, convert it to uppercase, and then print the third character of the resulting string.

3. Create a variable storing your age as an integer. Convert it to a string and concatenate it with the phrase "I am " at the beginning and " years old" at the end. Print the result.

4. Given the numbers 17 and 5, calculate and print the result of integer division and the remainder when 17 is divided by 5.

## Medium Exercises
1. Given a temperature in Celsius as a float, convert it to Fahrenheit using the formula: F = (C * 9/5) + 32. Round the result to two decimal places.

2. Create a string containing a sentence. Count how many times the letter 'a' (case-insensitive) appears in the sentence. Then, replace all occurrences of the word 'the' with 'a' and print the result.

## Hard Exercises

1. Implement the quadratic formula to find the roots of a quadratic equation ax^2 + bx + c = 0. Take a, b, and c as input (assume they're always valid) and print the roots. Handle cases where the discriminant is negative, zero, or positive.

2. Given a string representing a mathematical expression using only addition and subtraction (e.g., "5-2+3-1"), evaluate the expression and print the result. Assume all numbers in the expression are single-digit positive integers.

## Very Hard Exercise

1. Implement a function that takes a positive integer n and returns the nth Fibonacci number. Your implementation should be efficient enough to calculate F(1000) quickly. Hint: Consider using memoization or an iterative approach instead of naive recursion. After implementing the function, use it to find the last 3 digits of F(2024).


In [ ]:
# Space for exercises


## Lists and Dictionaries

A list in Python is an ordered collection of items that can store elements of different types, including integers, strings, and even other lists. Lists are _mutable_, meaning their contents can be changed after creation. In Python, one list can contain multiple data types, which is uncommon in other programming languages.

In [ ]:
l1 = [0, 1, 2, 3]
l2 = ['alabama', 'alaska', 'arizona']
l3 = [12.0+3j, 'potatoes', True, l1] # Notice how we put a list inside of this list!

# we forgot arkansas! Let's add it to our list after the fact
l2 = l2 + ['arkansas']

# check that we have 4 states that start with a
print(len(l2))
print(l2)

4
['alabama', 'alaska', 'arizona', 'arkansas']


We'll learn more about list operations later, but for now let's learn how to index lists and call member of a list. In Python, indexing begins with 0 (like we saw with strings!).

In [ ]:
print(f'We have defined {l1[3]} lists')
print(f'We are in {l2[2]}')
print(f'The first list we defined is {l3[-1]}')

We have defined 3 lists
We are in arizona
The first list we defined is [0, 1, 2, 3]


You can access elements of a list using indexing and slicing. Indexing lets you retrieve a single element from the list by specifying its position, while slicing allows you to extract a portion of the list by specifying a range of positions, including a start and an end (though the end is non-inclusive).

In [ ]:
my_list = [10, 20, 30, 40, 50]

# Indexing: Accessing a single element
first_element = my_list[0]  # Access the first element (10)
third_element = my_list[2]  # Access the third element (30)
last_element = my_list[-1]  # Access the last element using negative indexing (50)

print(f'First element: {first_element}')
print(f'Third element: {third_element}')
print(f'Last element: {last_element}')

# Slicing: Accessing a sublist
sublist_1 = my_list[1:4]  # Access elements from index 1 to 3 (20, 30, 40)
sublist_2 = my_list[:3]   # Access elements from the start up to index 2 (10, 20, 30)
sublist_3 = my_list[2:]   # Access elements from index 2 to the end (30, 40, 50)
sublist_4 = my_list[-3:-1] # Access elements using negative indexing (30, 40)

print(f'Sublist 1: {sublist_1}')
print(f'Sublist 2: {sublist_2}')
print(f'Sublist 3: {sublist_3}')
print(f'Sublist 4: {sublist_4}')


First element: 10
Third element: 30
Last element: 50
Sublist 1: [20, 30, 40]
Sublist 2: [10, 20, 30]
Sublist 3: [30, 40, 50]
Sublist 4: [30, 40]


To add elements to a list, you can use the `append` or `extend` method. `append` adds a single element, while `extend` adds multiple elements.

In [ ]:
#What if I want to add more elements?
my_list.append([1,2,3])
print(my_list)
my_list.extend([1,2,3]) #equivalent to scores + [1,2,3]
print(my_list)

[10, 20, 30, 40, 50, [1, 2, 3]]
[10, 20, 30, 40, 50, [1, 2, 3], 1, 2, 3]


Notice how in the first line of code, the whole list got added as a single element in the list, but in the second the list was extended to include the new list!

There are other useful functions that can be applied to lists:

In [ ]:
scores = [50.2, 28.3, 9.1, 0.5]
print("Starting scores:", scores)

# You can insert a value using scores.insert(a,b)
# a is the index where you'd like to insert, b is the value you want to insert
scores.insert(3, -3.5)
print("Scores after inserting:", scores)

# scores.remove finds the first instance of the data you give it and removes it
scores.remove(50.2)
print("Scores after removing:", scores)

# Pop removes the last element of the list and returns that element
# So you can store it as a new variable
P = scores.pop()
print("Scores after pop:", scores)
print("Popped value:", P)

# reverse reverses the order of the list
scores.reverse()
print("Scores after reversing:", scores)

# clear removes everything in the list
scores.clear()
print("Scores after clearing:", scores)

# copy creates a new copy of the list
C = scores.copy()
print("Copied scores:", C)

Starting scores: [50.2, 28.3, 9.1, 0.5]
Scores after inserting: [50.2, 28.3, 9.1, -3.5, 0.5]
Scores after removing: [28.3, 9.1, -3.5, 0.5]
Scores after pop: [28.3, 9.1, -3.5]
Popped value: 0.5
Scores after reversing: [-3.5, 9.1, 28.3]
Scores after clearing: []
Copied scores: []


Python also provides other variable types that serve as collections of things, e.g. tuples, dictionaries, sets, etc. We won't go over all of these, but let's look at dictionaries. Dictionaries are an unordered collection of items that are indexed by strings. We call the indexing string the `key`.

In [ ]:
jake = {'age': 28,
         'year_in_program': 2,
         'home_state': 'utah'}
# Oh no, we forgot a field we wanted to include. Let's add it after the fact
jake['is_TA'] = True

# now, to access an item from the dictionary, we must use the key.
# You can see what keys a dictionary has like so:
print(jake.keys())

print('brian is from')
print(jake['home_state'])

# you can also save the key as a variable and index the dictionary with the
# string variable
key_of_interest = 'is_TA'
print('Jake is a TA?')
print(jake[key_of_interest])

dict_keys(['age', 'year_in_program', 'home_state', 'is_TA'])
brian is from
utah
Jake is a TA?
True


# Lists and Dictionaries Exercises

## Easy Exercises

1. Create a list of the first 5 prime numbers. Then, append the next prime number to this list. Print the resulting list.

2. Given the list [1, 2, 3, 4, 5], create a new list containing only the even numbers from the original list. Try to do this using the list operations above, and not just by typing a new list.

3. Create a dictionary where the keys are the names of three countries, and the values are their respective capitals. Print the capital of the second country you added.

4. Given the list ["apple", "banana", "cherry", "date", "elderberry"], use list slicing to create a new list containing only the second, third, and fourth items.

## Medium Exercises

1. Start with the list [1, 2, 3, 4, 5]. Perform the following operations:
   a) Square each number in the list
   b) Remove all even numbers
   c) Insert the sum of the remaining numbers at the beginning of the list
   d) Sort the list in descending order
   Print the list after each operation.

2. Create a dictionary of student names and their scores on three tests. Calculate and store the average score for each student in a new dictionary. Then, create another dictionary containing only the students whose average score is above the overall average of the class.

3. Given a list of integers, find the longest consecutive sequence of numbers in the list. For example, if the input is [100, 4, 200, 1, 3, 2], the output should be [1, 2, 3, 4]. If there are multiple sequences of the same length, return any one of them.

## Hard Exercises

1. Given a list of integers, create a new list where each element is the product of all other elements in the original list, without using division. For example, if the input is [1, 2, 3, 4], the output should be [24, 12, 8, 6].

2. Create a dictionary where the keys are words and the values are lists of indices where those words appear in a given string. Ignore punctuation and treat words as case-insensitive. For example, given the string "The quick brown fox jumps over the lazy dog", the entry for "the" would be [0, 6].

## Very Hard Exercise
1. Create a function that takes a list of dictionaries, where each dictionary represents a product with the keys `"name"`, `"price"`, and `"quantity"`. Your task is to:
  1. Sort the list of products by `"price"` in descending order.
  2. After sorting, create a new dictionary that groups the products by the first letter of the `"name"`. The keys of this dictionary should be the first letters, and the values should be lists of products (dictionaries) that start with that letter.
  3. For each group, calculate the total inventory value (sum of `price * quantity`) and store this in a new dictionary where the keys are the group letters and the values are the total inventory value.

- Example:
  ```python
  products = [
      {"name": "apple", "price": 5, "quantity": 50},
      {"name": "banana", "price": 2, "quantity": 150},
      {"name": "avocado", "price": 8, "quantity": 30},
      {"name": "cherry", "price": 10, "quantity": 20},
  ]


In [ ]:
# space for exercises


### Control Flow
 1. python indentation
 2. `if/else`
 3. `range`
 4. `for` loop
 5. `while` loop
 6. `break` and `continue`

#### If/Else
`If/else` statements are one of the most essential concepts in any programming language. They allow your code to make decisions based on certain conditions. A condition is simply a statement that can either be `true` or `false`. When you write an `if/else` statement, the code first checks the condition:
- If the condition is `true`, the code inside the `if` block runs.
- If the condition is `false`, the code inside the `else` block runs instead.

This helps your program choose between different actions depending on the situation.

Typical operators used for comparison are:
- `==` checks if two things are equal
- `<` and `<` check strict inequality
- `<=` and `>=` check for non-strict inequality

#### Conditions
Conditions are just simple statements that evaluate to `true` or `false`. You can also combine multiple conditions into one using logical operators like `and` and `or`:
- **`and`**: All conditions must be `true` for the combined condition to be `true`.
- **`or`**: At least one condition must be `true` for the combined condition to be `true`.

These operators let you build more complex decision-making processes in your code. Try out changing the values in the conditions below to see how the results change.

In [ ]:
# Example 1: Basic if/else statement
temperature = 100

if temperature >= 100:
    print("It's a typical day in Tucson.")
else:
    print("Enjoy the nice cool weather!")

It's a typical day in Tucson.


In [ ]:
# Example 2: Combining conditions with 'and'
is_monsoon_season = True
clouds_rolling_in = False

if is_monsoon_season and clouds_rolling_in:
    print("Get ready for a monsoon!")
else:
    print("It might be a dry day despite the season.")

It might be a dry day despite the season.


In [ ]:
# Example 3: Combining conditions with 'or'
time_of_day = "night"

if time_of_day == "night" or time_of_day == "early morning":
    print("Watch out for javelinas—they're most active during this time.")

else:
    print("You probably won't see a javelina right now.")

Watch out for javelinas—they're most active during this time.


In [ ]:
# Example 4: Nested if/else statements
season = "spring"
ocotillo_in_bloom = True

if season == "spring":
    if ocotillo_in_bloom:
        print("The ocotillos are blooming beautifully! Great time for a hike.")
    else:
        print("Keep an eye out for the ocotillo blooms—they should start soon.")
else:
    print("The ocotillos are dormant; they usually come out in the spring.")

The ocotillos are blooming beautifully! Great time for a hike.


#### Loops
In Python, `for` loops are a way to repeat actions over a sequence of items, like elements in a list or numbers in a range. The `range()` function is often used with `for` loops to generate a sequence of numbers.

#### Range
The `range()` function creates a sequence of numbers. It's commonly used to loop through a specific number of times. You can use `range()` in several ways:
- **`range(stop)`**: Generates numbers from 0 up to (but not including) `stop`.
- **`range(start, stop)`**: Generates numbers from `start` up to (but not including) `stop`.
- **`range(start, stop, step)`**: Generates numbers from `start` to `stop`, with a step (increment/decrement) between each number.

#### For Loops
A `for` loop allows you to iterate over a sequence (like a list, string, or the numbers generated by `range()`) and execute a block of code for each item in the sequence. For example, you can use a `for` loop to repeat an action a specific number of times or to perform operations on each element in a list.

Together, `range()` and `for` loops make it easy to automate repetitive tasks, iterate through sequences, and manage loops efficiently.


In [ ]:
range(10)

range(0, 10)

In [ ]:
range(1,10)

range(1, 10)

In [ ]:
range(1,10,2)

range(1, 10, 2)

In [ ]:
# range(stop)
print("range(5):")
for num in range(5):
    print(num)  # Outputs: 0, 1, 2, 3, 4


In [ ]:
# range(start, stop)
print("\nrange(2, 6):")
for num in range(2, 6):
    print(num)  # Outputs: 2, 3, 4, 5


In [ ]:
# range(start, stop, step)
print("\nrange(1, 10, 2):")
for num in range(1, 10, 2):
    print(num)  # Outputs: 1, 3, 5, 7, 9


In [ ]:
print("\nrange(10, 0, -2):")
for num in range(10, 0, -2):
    print(num)  # Outputs: 10, 8, 6, 4, 2


In [ ]:
# Loop through a list of items
fruits = ["apple", "banana", "cherry"]
print("\nLooping through a list of fruits:")
for fruit in fruits:
    print(fruit)  # Outputs: apple, banana, cherry

In [ ]:
# Loop through a string (character by character)
word = "Tucson"
print("\nLooping through the characters in a string:")
for letter in word:
    print(letter)  # Outputs: T, u, c, s, o, n

#### for loop
Many times we want to iterate over a collection, and perform an action for each member of that collection.

In [ ]:
for i in range(10):
  print(i)

In [ ]:
for i in range(1,10):
  print(i)

In [ ]:
for i in range(1, 10, 2):
  print(i)

In [ ]:
x = [1, 2, 5, 7, 8, 3, 10];
for i in range(len(x)):
    print(x[i]+1)


for idx, num in enumerate(x):
  print(idx)
  print(num)

In [ ]:
for i in range(len(x)):
    if (x[i] > 5):
        print(x[i]+1);
    else:
        print(x[i]-1);

### While Loops

A `while` loop allows you to repeatedly execute a block of code as long as a specified condition is `true`. Unlike `for` loops, which iterate over a sequence, `while` loops keep running until the condition becomes `false`.

#### Basic Structure
The basic structure of a `while` loop looks like this:

```
while condition:
    # code to execute repeatedly
```
<u>Warning: `while` loops are an easy way to create an infinite loop.</u>

In [ ]:
# Example 1: Basic while loop
count = 0

print("Counting to 5:")
while count < 5:
    print(count)
    count += 1  # Increment count by 1 each time

In [ ]:
# Example 2: Using a while loop to simulate a process
temperature = 105  # Starting temperature in degrees Fahrenheit

print("\nCooling down:")
while temperature > 98:
    print(f"Temperature: {temperature}°F")
    temperature -= 1  # Decrease temperature by 1 degree each time

print("The temperature is now comfortable.")


In [ ]:
# Example 3: Countdown using a while loop
countdown = 10

print("\nCountdown:")
while countdown > 0:
    print(countdown)
    countdown -= 1  # Decrease countdown by 1 each time

print("Liftoff!")

In [ ]:
# Example 4: Popping a list using a while loop
x = [1, 2, 5, 7, 8, 3, 10]

while (len(x) >= 1):
    print(x)
    x.pop()

[1, 2, 5, 7, 8, 3, 10]
[1, 2, 5, 7, 8, 3]
[1, 2, 5, 7, 8]
[1, 2, 5, 7]
[1, 2, 5]
[1, 2]
[1]


#### break and continue
`break` and `continue` are more advanced controls used within loops and conditionals. `break` tells the program to leave the code block, whether the block is an `if/else` or a loop. `continue` is used within loops to stop processing the current iteration, and begin the next.

These have their applications, but there is almost always a better way that avoids using them.

In [ ]:
x = [1, 2, 5, 7, 8, 3, 10];
while (len(x) >= 1):
    if (x[-1] < 5):
        del(x[-1]);
        continue;
    elif (x[-1] == 5):
        break;
    else: #x > 5
        print(x[-1]*2);
        del(x[-1]);
print(x)

# Control Flow Exercises

## Easy Exercises

1. Write a program that takes a number as input. If the number is divisible by 3, print "Fizz". If it's divisible by 5, print "Buzz". If it's divisible by both 3 and 5, print "FizzBuzz". Otherwise, print the number itself.

2. Use a for loop and the range() function to print the first 10 even numbers (2, 4, 6, ..., 20).

3. Create a while loop that starts with x = 0 and increments x by 1 in each iteration. Break the loop when x becomes greater than 5. Print the value of x in each iteration.

4. Write a program that prints the numbers from 1 to 20. For multiples of 3, print "Three" instead of the number. Use continue to skip even numbers.

## Medium Exercises

1. Create a list of numbers from 1 to 100. Use a for loop to iterate through this list and print only the prime numbers. Use the continue keyword to skip non-prime numbers.

2. Write a program that simulates a simple guessing game. Generate a random number between 1 and 100, then use a while loop to allow the user to guess the number. Provide "too high" or "too low" feedback after each guess. Use break to exit the loop when the correct number is guessed.

3. Create a nested loop structure to print a right-angled triangle pattern of x characters. The number of rows should be based on user input. For example, if the user inputs 5, the output should be:  
x   
xx  
xxx  
xxxx  
xxxxx  

## Hard Exercises

1. Write a program to find all prime numbers up to a given number n. Use the following approach:
   - Create a list of all numbers from 2 to n.
   - Starting with the first number in the list (2), mark all its multiples as non-prime.
   - Move to the next unmarked number and repeat the process.
   - Continue until you've processed all numbers up to the square root of n.
   Use nested loops and the break keyword to implement this efficiently. The remaining unmarked numbers in your list will be prime.

2. Write a program that finds the longest palindromic substring in a given string. Use nested loops and if/else statements to check for palindromes of different lengths. For example, in the string "babad", the longest palindromic substring is "bab" or "aba".

## Very Hard Exercise

1. Create a program that simulates a cellular automaton on a 2D grid. The program should:

   a) Allow the user to:
      - Set the grid size (e.g., 20x20)
      - Define the initial state of cells (e.g., 'alive' or 'dead', represented by 1 or 0)
      - Specify the number of generations to simulate

   b) Implement the following rules for each cell in each generation:
      - A cell with fewer than two 'alive' neighbors becomes 'dead'
      - A cell with two or three 'alive' neighbors stays in its current state
      - A cell with more than three 'alive' neighbors becomes 'dead'
      - A 'dead' cell with exactly three 'alive' neighbors becomes 'alive'

   c) Consider all eight neighboring cells (horizontal, vertical, and diagonal)

   d) Update all cells simultaneously in each generation

   e) Print the state of the grid after each generation

   Use appropriate control structures (if/else, for/while loops, break/continue) to implement this simulation efficiently. Pay special attention to handling the edges of the grid correctly.


In [ ]:
# space for exercises



### Lists

Basic list functions

### Mini exercise:
What do the averages list and k list look like after this sequence of commands?

averages = []

averages = averages +  [5, 3, 8, 2.2, -4]

k = averages

k.reverse()

k.insert(3, 0)

k = k + [0,0,0]


In [ ]:
#Space for checking solution (do on paper first!)


### List manipulation with loops and conditionals

In [ ]:
scores = [5, 3, 8, 2.2, -4]
#Let's write a loop to calculate the arithmetic mean of a numerical list
A = 0
for i in scores:
    A += i
A = A/len(scores) #calculates the length of the scores list
print(A)

#OR
A = 0
L = len(scores)
for i in range(0, L):
    A += scores[i]
A /= L
print(A)

#OR

A = 0
L = len(scores)
for index, val in enumerate(scores):
  A += scores[index]
  A += val
A /= 2*L
print(A)

In [ ]:
# Multi-dimensional lists
A = []
for i in range(1, 12, 3):
    A.append([i, i+1, i+2])
print(A)
#what about access?
print(A[1][2])

In [ ]:
#Ragged lists
B = []
for i in range(0, 5):
    B.append([])
    for j in range(0,i+1):
        B[i].append(j)
print(B)


# List Manipulation with Loops and Conditionals

## Easy Exercises

1. Given a list of numbers, create a new list that contains only the even numbers from the original list. Use a loop and conditional statement.

2. Write a program that takes a list of numbers and prints the largest number in the list using a loop.

3. Given a list of strings, create a new list that contains only the strings with more than 5 characters. Use a loop and conditional statement.

4. Write a program that takes a list of numbers and calculates the sum of all positive numbers in the list using a loop and conditional statement.

## Medium Exercises

1. Given a list of numbers, create two new lists: one containing all the positive numbers and another containing all the negative numbers from the original list. Use a single loop with conditional statements.

2. Write a program that takes a list of numbers and replaces each number with its absolute value. Modify the original list in-place using a loop.

3. Given a list of strings, create a new list where each string is reversed, but only if it has an even number of characters. Use a loop with conditional statements.

## Hard Exercises

1. Implement a bubble sort algorithm to sort a list of numbers in ascending order. Use nested loops and conditional statements to compare adjacent elements and swap them if they're in the wrong order. Print the list after each pass of the outer loop.

2. Given a list of integers, find all pairs of numbers whose sum is equal to a given target number. Use nested loops and conditional statements. For example, if the list is [1, 5, 3, 4, 2] and the target is 7, the output should be [(5, 2), (3, 4)].

## Very Hard Exercises

1. Implement a program that solves the "N-Queens" problem for a user-specified board size N. The N-Queens problem involves placing N chess queens on an N×N chessboard so that no two queens threaten each other. Your program should:

   a) Create a list of lists to represent the chessboard
   b) Use nested loops to attempt placing queens in different positions
   c) Use conditional statements to check if a queen can be placed in a given position (i.e., not under attack by any other queen)
   d) If a solution is found, print the board configuration (you can use 'Q' for queens and '.' for empty squares)
   e) If no solution is found, print "No solution exists"

Start with small values of N (e.g., 4 or 5) and work your way up to larger board sizes.

# Comprehensions

Now, let's look at a more concise way of generating new lists using list comprehension.
These do the same operations as a loop, but can be faster and more intuitive to write.

In [ ]:
#for loop
loop_list = []
for i in range(0,10):
  loop_list.append(i * 0.5)
print(loop_list)

#equivalent list comprehension
new_list = [x/2 for x in range(0,10)]
print(new_list)

In [ ]:
#throw in if statements to modify new_list
h_list = []
for i in new_list:
  if i%1 != 0: #can also say if i%1:
    h_list.append(i)
print(h_list)

#What about only the halfway points?
half_list = [h for h in new_list if h%1]
print(half_list)

In [ ]:
#making a true/false list
t_list = []
for i in new_list:
  t_list.append(i > 2)
print(t_list)

#list comprehension
tf_list = [x > 2 for x in new_list]
print(tf_list)

In [ ]:
#what about multidimensional lists?
multi_list = [[i, i+1] for i in new_list[5:]]
print(multi_list)

ragged_list = [[j for j in range(0,i+1)] for i in range(0,5)]
print(ragged_list)


### Basic Exercises

1) Write a loop that finds the maximum element in a list

2) Generate a list using list comprehension that stores whether an element in an original list is even or odd

3) Generate the loop versions of the list comprehension examples for ragged and multidimensional lists

### Medium Exercises

1) Create a multidimensional list of coordinate pairs as tuples with grid points every 0.1 units, starting from the lower left corner of quadrant three and building upwards.
Format should be like below, but with finer spacing:

[[(-1, -1), (-0.5, -1), (0, -1), (0.5, -1), (1,-1)],

[-1, -0.5), (-0.5, -0.5), (0, -0.5), (0.5, -0.5), (1, -0.5)]

...]

2) Do the same, but exclude grid points that in any way involve the number 7.

In [ ]:
#write your solutions here

#Functions
Here, we discuss the basics regarding functions


In [ ]:
#First, we define a function with no input and no return value

def useless_function():
    k = 3
    list_k = [n for n in range(1,k)]
    print(list_k)

#We can call the function as such:
U = useless_function()
print(U)

[1, 2]
None


In [ ]:
#one input, one output.
#For any positive integer N, returns a list of all factors of N.
#input: N, integer
#output: List containing all factors of N.
def find_factors(N):
    factor_list = []
    for i in range(1,N+1):
        if N%i == 0:
            factor_list.append(i)
    return factor_list

find_factors(800)

[1, 2, 4, 5, 8, 10, 16, 20, 25, 32, 40, 50, 80, 100, 160, 200, 400, 800]

In [ ]:
#We can include as many inputs as we like, and determine outputs by the return keyword
#input_list, const "live inside" multiply_list.
def multiply_list(input_list, const):
    return [n * const for n in input_list]

M = multiply_list([1,2,3], 4)
print(M)
[1,2,3]*4

[4, 8, 12]


[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
#We can also give default values to function elements, or pass in other arguments not yet specified
def multiply_list_2(input_list, const = 3, **kwargs):
    for x in kwargs:
        print(x)
    return[n * const for n in input_list], const

res_list, const_val = multiply_list_2([1,2,3,4], 4, extra = 3, telluride = 4)

print(res_list)
print(const_val)

extra
telluride
[4, 8, 12, 16]
4


In [ ]:
#recursion -- you can call functions within themselves, but be sure to have a base case!
def factorial(n):
    if n <= 1:
        return 1
    return n*factorial(n-1)

print(factorial(20))

2432902008176640000


# Functions Exercises

## Easy Exercises

1. Write a function called `is_even` that takes an integer as an argument and returns True if the number is even, and False otherwise.

2. Create a function called `greet` that takes a name as an argument and returns a greeting string. For example, if the input is "Alice", it should return "Hello, Alice!".

3. Write a function called `calculate_area` that takes the radius of a circle as an argument and returns its area. Use the approximation 3.14 for pi.

4. Create a function called `reverse_string` that takes a string as an argument and returns the reversed string.

## Medium Exercises

1. Write a function called `fibonacci` that takes an integer n as an argument and returns the nth number in the Fibonacci sequence. (Assume the sequence starts with 0 and 1.)

2. Create a function called `is_palindrome` that takes a string as an argument and returns True if the string is a palindrome (reads the same forwards and backwards, ignoring spaces and punctuation), and False otherwise.

3. Write a function called `prime_factors` that takes an integer as an argument and returns a list of its prime factors.

## Hard Exercises

1. Create a function called `merge_sorted_lists` that takes two sorted lists as arguments and returns a new sorted list containing all elements from both input lists. Do not use Python's built-in sorting functions.

2. Write a recursive function called `power` that takes two arguments, base and exponent, and returns base raised to the exponent. Do not use the built-in power operator (**) or math functions.

## Very Hard Exercise

1. Implement a text analysis toolkit with the following functions:

   a) `word_frequency(text)`:
      - Input: A string of text
      - Output: A dictionary with words as keys and their frequencies as values
      - Should ignore punctuation and be case-insensitive

   b) `top_n_words(text, n)`:
      - Input: A string of text and an integer n
      - Output: A list of the n most frequent words, sorted by frequency

   c) `sentence_tokenize(text)`:
      - Input: A string of text
      - Output: A list of sentences
      - Should handle various sentence-ending punctuation (.!?)

   d) `cosine_similarity(text1, text2)`:
      - Input: Two strings of text
      - Output: A float between 0 and 1 representing the cosine similarity of the texts

   e) `summarize(text, num_sentences)`:
      - Input: A string of text and the desired number of sentences for the summary
      - Output: A summary of the text with the specified number of sentences
      - Use a simple extractive summarization technique (e.g., selecting the most representative sentences based on word frequency)

   f) `generate_ngrams(text, n)`:
      - Input: A string of text and an integer n
      - Output: A list of all n-grams in the text

   Implement these functions efficiently, handling edge cases and potential errors. Then, create a main function that demonstrates the use of all these functions on a sample text (you can use a famous speech or article).


# Numpy

NumPy (Numerical Python) is a fundamental library for scientific computing in Python, providing support for large, multi-dimensional arrays and matrices. Its core object is the ndarray (n-dimensional array), which allows for efficient operations on large datasets. NumPy's strength lies in its ability to perform rapid array-wise computations and its collection of mathematical functions.

NumPy is highly optimized for performance, making it much faster than traditional Python lists for numerical operations. It leverages low-level optimizations and provides an interface to C, C++, and Fortran libraries.

In [ ]:
# First, we need to import NumPy. It's common to import it as 'np'
import numpy as np

# Creating NumPy arrays

# 1. Creating an array from a Python list
list_array = np.array([1, 2, 3, 4, 5])
print("Array from list:", list_array)

# 2. Creating an array of zeros
zeros_array = np.zeros(5)
print("Array of zeros:", zeros_array)

# 3. Creating an array of ones
ones_array = np.ones(5)
print("Array of ones:", ones_array)

# 4. Creating an array with a range of values
range_array = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2
print("Array with range:", range_array)

# 5. Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array (matrix):\n", matrix)

Array from list: [1 2 3 4 5]
Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1.]
Array with range: [0 2 4 6 8]
2D array (matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Basic array operations and attributes

# 1. Array shape -- tells you how many rows and columns the array has, in that order
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)

# 2. Array dimensions -- tells you if the array is 1D, (a vector), 2D (a matrix), etc.
print("Number of dimensions:", arr.ndim)

# 3. Total number of elements
print("Total elements:", arr.size)

# 4. Data type of elements
print("Data type:", arr.dtype)

# 5. Reshaping arrays
reshaped = arr.reshape(3, 2)
print("Reshaped array:\n", reshaped)

# 6. Flattening arrays
flattened = arr.flatten()
print("Flattened array:", flattened)

Array shape: (2, 3)
Number of dimensions: 2
Total elements: 6
Data type: int64
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened array: [1 2 3 4 5 6]


In [ ]:
# Array indexing and slicing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Array:\n', arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Indexing arrays -- Arrays are indexed in the row, column order. Note that indexing starts at 0!
print("Element at row 1, column 2:", arr[1, 2])

# Slicing -- You can use a colon as a placeholder for several rows or columns.
# A single colon in the column (or row) spot will select every column (or row):

print("First column:\n", arr[:, 0])
print("First row:\n", arr[0,:])

#You can also use a colon combined with an integer to select parts of a row or column
# For example, :2 selects everything up to (but not including) 2.
# On the other hand, 2: selects 2 and everything afer it.
print("First three elements of the first column:\n", arr[:3, 0])
print("First three elements of the first row:\n", arr[0, :3])
print("First three rows:\n", arr[:3,:]) # Notice here we're selecting the first three rows and EVERY column.

Element at row 1, column 2: 7
First column:
 [1 5 9]
First row:
 [1 2 3 4]
First three elements of the first column:
 [1 5 9]
First three elements of the first row:
 [1 2 3]
First three rows:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Boolean indexing
# You can index arrays using True/False values!
bool_index = arr > 5
print('Indexing array:', bool_index)

# Here, bool_index is an array of the same shape as arr
# each element of bool_index says where to select the
# corresponding index of arr
print("Elements greater than 5:\n", arr[bool_index])

# Fancy indexing
# You can also index with a list to select specific rows
fancy_index = np.array([0, 2])
print("First and third rows:\n", arr[fancy_index])

Indexing array: [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Elements greater than 5:
 [ 6  7  8  9 10 11 12]
First and third rows:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
# Mathematical operations with NumPy arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
C = np.array([[1,2,4],[5,6,7],[8,9,10]])
D = np.array([[11,12,13],[14,15,16],[17,18,19]])

# 1. Element-wise addition
print("a + b =", a + b)

# 2. Element-wise subtraction
print("a - b =", a - b)

# 3. Element-wise multiplication
print("a * b =", a * b)

# 4. Element-wise division
print("a / b =", a / b)

# 5. Scalar operations
print("a * 2 =", a * 2)

# 6. Sum of all elements
print("Sum of a:", np.sum(a))

# 7. Mean of all elements
print("Mean of a:", np.mean(a))

# 8. Maximum and minimum
print("Max of a:", np.max(a))
print("Min of a:", np.min(a))

# 10. Matrix multiplication
print('CD:', C@D)
print('C^TD:', C.T@D)
print('Ca:', C@a)
print('a^T C:', a.T@C)
print('aC:', a@C) # Notice how numpy automatically matches the shapes for you

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a * 2 = [2 4 6]
Sum of a: 6
Mean of a: 2.0
Max of a: 3
Min of a: 1
CD: [[107 114 121]
 [258 276 294]
 [384 411 438]]
C^TD: [[217 231 245]
 [259 276 293]
 [312 333 354]]
Ca: [17 38 56]
a^T C: [35 41 48]
aC: [35 41 48]


### Other capabilities

Numpy comes with built in support for operations on arrays
in lots of different areas:

**Linear Algebra**: NumPy has robust support for linear algebra operations, including matrix multiplication, determinants, eigenvalues, and solving systems of linear equations. It also provides functions for working with vectors and matrices efficiently.


In [ ]:
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [ ]:
# Determinant of a matrix
det_A = np.linalg.det(A)
print("\nDeterminant of A:")
print(det_A)


Determinant of A:
-2.0000000000000004


In [ ]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)


Eigenvalues of A:
[-0.37228132  5.37228132]
Eigenvectors of A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# Calculating the norm of a vector
vector = np.array([3, 4])

# Calculate different norms of the vector
norm_2 = np.linalg.norm(vector, ord=2) # the ord keyword specifies the type of norm to use
norm_inf = np.linalg.norm(vector, ord=np.inf) # you can use np.inf for infinity

# Calculate Frobenius norm of a matrix
fro_norm = np.linalg.norm(A, ord='fro')

print("Vector:", vector)
print("2 norm:", norm_2)
print("infinity norm:", norm_inf)

print("Matrix A:", A)
print("Frobenius norm:", fro_norm)

Vector: [3 4]
2 norm: 5.0
infinity norm: 4.0
Matrix A: [[1 2]
 [3 4]]
Frobenius norm: 5.477225575051661



**Random Number Generation**: NumPy includes a random module for generating random numbers. You can generate random numbers from various distributions, create random samples, and perform random shuffling.

In [ ]:
# Generate a 3x3 array of random numbers from a uniform distribution
random_array = np.random.rand(3, 3)
print("3x3 Array of Random Numbers:")
print(random_array)

# Generate random integers between 0 and 10
random_integers = np.random.randint(0, 10, size=5)
print("\nArray of Random Integers:")
print(random_integers)

# Shuffle a list randomly
array_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array_to_shuffle)
print("\nShuffled Array:")
print(array_to_shuffle)

3x3 Array of Random Numbers:
[[0.59494821 0.63574694 0.99774812]
 [0.74851054 0.39982304 0.93253208]
 [0.0475475  0.5203693  0.14793072]]

Array of Random Integers:
[9 0 5 3 9]

Shuffled Array:
[3 4 5 2 1]

Statistical Functions Example:
Mean:
28.0

Median:
20.0

Standard Deviation:
14.696938456699069

Variance:
216.0


**Statistical Functions**: NumPy offers a wide range of statistical functions to compute mean, median, standard deviation, variance, and more. These functions are optimized for performance and can handle large datasets.

In [ ]:
# Create an array of data
data = np.array([10, 20, 20, 40, 50])

# Calculate mean
mean_value = np.mean(data)
print("Mean:")
print(mean_value)

# Calculate median
median_value = np.median(data)
print("\nMedian:")
print(median_value)

# Calculate standard deviation
std_dev = np.std(data)
print("\nStandard Deviation:")
print(std_dev)

# Calculate variance
variance = np.var(data)
print("\nVariance:")
print(variance)

Mean:
28.0

Median:
20.0

Standard Deviation:
14.696938456699069

Variance:
216.0



**Numerical Integration**: NumPy includes tools for numerical integration, allowing you to approximate the integral of a function, which is essential in many scientific and engineering applications.

In [ ]:
# Define the function to integrate
def f(x):
    return np.sin(x)

# Create an array of 1000 x-values from 0 to pi
x = np.linspace(0, np.pi, 1000)

# Evaluate the function at each x value
y = f(x)

# Perform numerical integration using the trapezoidal rule
integral = np.trapz(y, x)

print("Numerical Integration Result using trapezoidal rule:")
print(integral)

Numerical Integration Result using trapezoidal rule:
1.999998351770852


# NumPy Exercises

## Easy Exercises

1. Create a 1D NumPy array of 10 random integers between 1 and 100. Then, print all elements greater than 50.

2. Create a 2D NumPy array with shape (3, 3) containing random float numbers between 0 and 1. Calculate and print the sum of each column.

3. Given the array `arr = np.array([1, 2, 3, 4, 5])`, create a new array where each element is the square of the corresponding element in `arr`.

4. Create two 1D arrays, each with 5 random integers between 1 and 10. Perform element-wise multiplication of these arrays and print the result.

## Medium Exercises

1. Create a 2D array of shape (5, 5) containing random integers between 1 and 25. Then, replace all even numbers with 0 and all odd numbers with 1.

2. Given an array `arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])`, use NumPy operations to reverse the array, then reshape it into a 2x5 matrix.

3. Create a 1D array of 20 linearly spaced numbers between 0 and 1. Then, reshape this array into a 4x5 matrix and compute the mean of each row.

## Hard Exercises

1. Create a 2D array of shape (10, 10) containing random integers between 1 and 100. Find and print the indices of the minimum value in each row using NumPy functions.

2. Given two 2D arrays `A` and `B`, both of shape (3, 3), compute the matrix product of A and B using NumPy. Then, calculate the determinant of the resulting matrix.

## Very Hard Exercise

Implement a function `subspace_projector(A)` that does the following:

1. Take as input a matrix A of shape (m, n), where m > n.

2. Compute the reduced QR decomposition of A using NumPy's `np.linalg.qr()` with mode='reduced'.

3. Using the Q from the QR decomposition, create a function `project(v)` that:
   a) Takes a vector v of length m
   b) Projects v onto the column space of A
   c) Returns both the projected vector and the component of v orthogonal to the column space of A

4. Implement a function `is_in_column_space(v, tolerance=1e-8)` that:
   a) Takes a vector v of length m
   b) Returns True if v is in the column space of A (up to the given tolerance), False otherwise

5. Create a function `find_basis_for_nullspace()` that:
   a) Computes the singular value decomposition (SVD) of A
   b) Uses the singular values to determine the dimension of the nullspace
   c) Returns a matrix whose columns form an orthonormal basis for the nullspace of A

Test your implementation with:
1. A random 5x3 matrix
2. A matrix with linearly dependent columns
3. A matrix close to having linearly dependent columns (to test numerical stability)

For each test case:
- Print the original matrix A
- Project a random vector onto the column space of A and print both components
- Test if various vectors are in the column space of A
- Print the basis for the nullspace of A

This exercise combines several key concepts in linear algebra:
- QR decomposition
- Orthogonal projections
- Column space and nullspace
- Singular Value Decomposition
- Numerical tolerance in computations

It requires understanding of these concepts as well as careful use of NumPy functions and array manipulations.